server:
  port: 6002

# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/orderdb
#     username: postgres
#     password: password

#   kafka:
#     bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  boot:
    admin:
      client:
        url: http://localhost:9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
